### ISSUE TITLE
Question regarding manpages

### ISSUE THREAD

**Issue by wjk** [canonical/core-base-desktop#50]
I’m new here and trying to learn all about the core-desktop project, so please forgive me if this is a stupid question.

In this repo, there is a version of `/usr/bin/man` that states manpages have been removed from the core image, and to use the [manpages.ubuntu.com](https://manpages.ubuntu.com) website instead. In the core image, this is fine. But what if the user were to want to read a manpage, since core-desktop is meant to be used interactively? Also, how do snaps contribute manpages for their commands, if they can do so at all? As a user, I would find a message telling me to look up my manpage online unfriendly, especially if I have experience with “regular” Ubuntu, where the manpages are always present. And what if the reason the user needs the manpage is because they are debugging a networking problem, so they can’t get to the website?

**Comment by robert-ancell** [comment]
Hi! There are no stupid questions :)

The core image is intentionally minimal. We haven't worked out all the details yet but a developer is expected to use packages built on top of core, likely using containers or VMs to develop in. These would contain all the tooling required including man pages.

**Comment by wjk** [comment]
Another question. I understand that you are expected to develop in containers. That wasn’t what I was asking about. I was talking about the terminal-emulator app and the programs you would expect a user to be able to run from there. I don’t want to have to install a huge container just to use `zsh` with my files, and not being able to see the manpage for `lxc` makes it impossible to learn how to use the program properly (all I can do is blindly retype the commands in a blog post), which I think is a Bad Thing.

**Comment by robert-ancell** [comment]
I wouldn't expect the terminal app as it is currently in the image to be the final experience. It's really just there currently for debugging purposes. So the default terminal might automatically be a container, or it might give you information about its limitation and show you how to use a container or something else. We agree that the experience after first install should be great!

**Comment by wjk** [comment]
And one other question. If the terminal app launches in a container by default, that’s brilliant. I just need to know how I can run `snap` from the terminal app and have it affect the host system instead of inside of the container. (Or run command-line tools installed by snaps.)
